### ISSUE TITLE
Using GitHub

### ISSUE THREAD

**Issue by martinRobinson** [PatDoohan/Garda-Case-Lookup-Database#1]
Remember to commit each functional change to your prototype and make each commit message informative.

**Comment by PatDoohan** [comment]
Ok will do thanks martin, are you able to see the project or do you require access to it?

**Comment by martinRobinson** [comment]
Hi Pat,
I am working with another student and couldn’t find his repository so I searched for LYIT and found yours.
I can see the project but I don’t need access to it.
You should try to get the other members of the team to check in some code and/or changes.
Regards
Martin
