### ISSUE TITLE
Team members

### ISSUE THREAD

**Issue by martinRobinson** [PatDoohan/Garda-Case-Lookup-Database#4]
Hi Pat,
If you have a chance could you look into how to make your fellow team members full collaborators in the GitHub project. I would like to see each team member's contributions in the graphs section of the repository. Also if they are using nicknames or their L student numbers, ask them to change their GitHub names to something recognisable.
Thanks
Martin

**Comment by PatDoohan** [comment]
Hi Martin, 
Sorry i didn't get a notification on this when it was posted and someone only brought it to my attention recently, I think i did add the members as full contributors, but i will check again just to be sure. We were having issues getting git working on some of the other IDE's so half the team decided to not to focus on it and actually get the work done, all my commits are just my programming, anything that was developed by the others was just copied over using physical storage. I believe caolan recently got his git working so you can expect more commits from him and the same once we can get hugh and tristans git pushing and pulling working,

However it is not a priority for us at the moment as the project is still being developed at a reasonable pace without github, if we can get it working properly we will try and make the changes on github, As Caolans is working i believe that we should all be using it soon.
